In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("data/owid-covid-data.csv")
display(df.head())

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [10]:
list = [52330, 159409, 218700, 92675, 513510, 670, 157, 378, 87071, 227420, 8846, 423262, 235749, 294494, 201196, 150584, 81034, 41, 181503, 46, 113010, 13757, 1195, 124630, 260593, 0, 128867, 482178, 138004, 474064, 143834, 362741, 58599, 61769, 43299, 11434, 799, 13665, 6884, 44, 0, 207822, 77060, 1465, 2099]

print(len(list))
print(max(list))

45
513510

In [8]:
# df = df.drop(['new_cases_smoothed', 'new_deaths_smoothed', 'new_cases_smoothed_per_million', 'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients', 'icu_patients_per_million', 'hosp_patients', 'hosp_patients_per_million', 'weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'new_tests', 'total_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'positive_rate', 'tests_per_case', 'tests_units', 'new_vaccinations_smoothed', 'new_vaccinations_smoothed_per_million', 'new_people_vaccinated_smoothed', 'new_people_vaccinated_smoothed_per_hundred', 'stringency_index', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million'], axis=1)

In [ ]:
# asia_df = df[df["continent"] == "Asia"]
# display(asia_df)
# asia_df.to_csv("data/asia.csv", index=False)

In [10]:
# india_df = df[df["location"] == "India"]
# display(india_df)
# india_df.to_csv("data/india.csv", index=False)

,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,...,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,population
69875,IND,Asia,India,2020-01-30,1.0,1.0,NaN,NaN,0.001,0.001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.393409e+09
69876,IND,Asia,India,2020-01-31,1.0,0.0,NaN,NaN,0.001,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.393409e+09
69877,IND,Asia,India,2020-02-01,1.0,0.0,NaN,NaN,0.001,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.393409e+09
69878,IND,Asia,India,2020-02-02,2.0,1.0,NaN,NaN,0.001,0.001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.393409e+09
69879,IND,Asia,India,2020-02-03,3.0,1.0,NaN,NaN,0.002,0.001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.393409e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70638,IND,Asia,India,2022-03-03,42951556.0,6396.0,514589.0,201.0,30824.801,4.590,...,1.781445e+09,966508496.0,795778169.0,19158374.0,3191366.0,127.85,69.36,57.11,1.37,1.393409e+09
70639,IND,Asia,India,2022-03-04,42957477.0,5921.0,514878.0,289.0,30829.050,4.249,...,1.784081e+09,966810216.0,797997103.0,19274125.0,2636405.0,128.04,69.38,57.27,1.38,1.393409e+09
70640,IND,Asia,India,2022-03-05,42962953.0,5476.0,515036.0,158.0,30832.980,3.930,...,1.786849e+09,967153861.0,800304849.0,19390638.0,2767904.0,128.24,69.41,57.44,1.39,1.393409e+09
70641,IND,Asia,India,2022-03-06,42967315.0,4362.0,515102.0,66.0,30836.111,3.130,...,1.787846e+09,967279389.0,801141086.0,19425033.0,996160.0,128.31,69.42,57.50,1.39,1.393409e+09
70642,IND,Asia,India,2022-03-07,42971308.0,3993.0,515210.0,108.0,30838.976,2.866,...,1.789317e+09,967460932.0,802358408.0,19497788.0,1471620.0,128.41,69.43,57.58,1.40,1.393409e+09

In [11]:
asia_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36296 entries, 0 to 165350
Data columns (total 22 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   iso_code                             36296 non-null  object
 1   continent                            36296 non-null  object
 2   location                             36296 non-null  object
 3   date                                 36296 non-null  object
 4   total_cases                          35738 non-null  float64
 5   new_cases                            35713 non-null  float64
 6   total_deaths                         31922 non-null  float64
 7   new_deaths                           31903 non-null  float64
 8   total_cases_per_million              35738 non-null  float64
 9   new_cases_per_million                35713 non-null  float64
 10  total_deaths_per_million             31922 non-null  float64
 11  new_deaths_per_million               31903 non-null  float64
 12  total_vaccinations                   11330 non-null  float64
 13  people_vaccinated                    10224 non-null  float64
 14  people_fully_vaccinated              9403 non-null   float64
 15  total_boosters                       3052 non-null   float64
 16  new_vaccinations                     9639 non-null   float64
 17  total_vaccinations_per_hundred       11330 non-null  float64
 18  people_vaccinated_per_hundred        10224 non-null  float64
 19  people_fully_vaccinated_per_hundred  9403 non-null   float64
 20  total_boosters_per_hundred           3052 non-null   float64
 21  population                           35979 non-null  float64
dtypes: float64(18), object(4)
memory usage: 6.4+ MB