# F20DV - LAB 4

In [1]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("data/state_crime.csv")
display(df)

,State,Year,Data.Population,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,...,Data.Rates.Violent.Robbery,Data.Totals.Property.All,Data.Totals.Property.Burglary,Data.Totals.Property.Larceny,Data.Totals.Property.Motor,Data.Totals.Violent.All,Data.Totals.Violent.Assault,Data.Totals.Violent.Murder,Data.Totals.Violent.Rape,Data.Totals.Violent.Robbery
0,Alabama,1960,3266740,1035.4,355.9,592.1,87.3,186.6,138.1,12.4,...,27.5,33823,11626,19344,2853,6097,4512,406,281,898
1,Alabama,1961,3302000,985.5,339.3,569.4,76.8,168.5,128.9,12.9,...,19.1,32541,11205,18801,2535,5564,4255,427,252,630
2,Alabama,1962,3358000,1067.0,349.1,634.5,83.4,157.3,119.0,9.4,...,22.5,35829,11722,21306,2801,5283,3995,316,218,754
3,Alabama,1963,3347000,1150.9,376.9,683.4,90.6,182.7,142.1,10.2,...,24.7,38521,12614,22874,3033,6115,4755,340,192,828
4,Alabama,1964,3407000,1358.7,466.6,784.1,108.0,213.1,163.0,9.3,...,29.1,46290,15898,26713,3679,7260,5555,316,397,992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3110,Wyoming,2015,586107,179.8,1902.6,300.6,1500.9,222.1,10.1,2.7,...,21.3,1054,11151,1762,8797,1302,59,16,173,125
3111,Wyoming,2016,585501,1957.3,302.5,1518.2,136.6,244.2,195.7,3.4,...,10.1,11460,1771,8889,800,1430,1146,20,205,59
3112,Wyoming,2017,579315,1830.4,275.0,1421.0,134.5,237.5,176.4,2.6,...,13.1,10604,1593,8232,779,1376,1022,15,263,76
3113,Wyoming,2018,577737,1785.1,264.0,1375.9,145.2,212.2,150.6,2.3,...,17.3,10313,1525,7949,839,1226,870,13,243,100
3114,Wyoming,2019,578759,1571.1,241.2,1206.7,123.2,217.4,147.6,2.2,...,11.6,9093,1396,6984,713,1258,854,13,324,67

In [3]:
bool_series = df.duplicated()
display(bool_series)
print(bool_series[0])

0       False
1       False
2       False
3       False
4       False
        ...
3110    False
3111    False
3112    False
3113    False
3114    False
Length: 3115, dtype: bool

False

In [4]:
for i in range(3115):
    if(bool_series[i] == True):
        print(i)
        print(bool_series[i])

In [15]:
df.rename(columns={
    "State": "state", 
    "Year": "year", 
    "Data.Population": "population", 

    "Data.Rates.Property.All": "property_rates_all", 
    "Data.Rates.Property.Burglary": "rates_burglary", 
    "Data.Rates.Property.Larceny": "rates_larceny",
    "Data.Rates.Property.Motor": "rates_motor",

    "Data.Rates.Violent.All": "violent_rates_all",
    "Data.Rates.Violent.Assault": "rates_assault",
    "Data.Rates.Violent.Murder": "rates_murder",
    "Data.Rates.Violent.Rape": "rates_rape",
    "Data.Rates.Violent.Robbery": "rates_robbery",

    "Data.Totals.Property.All": "property_total_all",
    "Data.Totals.Property.Burglary": "total_burglary",
    "Data.Totals.Property.Larceny": "total_larceny",
    "Data.Totals.Property.Motor": "total_motor",

    "Data.Totals.Violent.All": "violent_total_all",
    "Data.Totals.Violent.Assault": "total_assault",
    "Data.Totals.Violent.Murder": "total_murder",
    "Data.Totals.Violent.Rape": "total_rape",
    "Data.Totals.Violent.Robbery": "total_robbery"
}, inplace = True)

display(df)
df.to_csv("data/crimeUS.csv", index=False)

,state,year,population,property_rates_all,rates_burglary,rates_larceny,rates_motor,violent_rates_all,rates_assault,rates_murder,...,rates_robbery,property_total_all,total_burglary,total_larceny,total_motor,violent_total_all,total_assault,total_murder,total_rape,total_robbery
0,Alabama,1960,3266740,1035.4,355.9,592.1,87.3,186.6,138.1,12.4,...,27.5,33823,11626,19344,2853,6097,4512,406,281,898
1,Alabama,1961,3302000,985.5,339.3,569.4,76.8,168.5,128.9,12.9,...,19.1,32541,11205,18801,2535,5564,4255,427,252,630
2,Alabama,1962,3358000,1067.0,349.1,634.5,83.4,157.3,119.0,9.4,...,22.5,35829,11722,21306,2801,5283,3995,316,218,754
3,Alabama,1963,3347000,1150.9,376.9,683.4,90.6,182.7,142.1,10.2,...,24.7,38521,12614,22874,3033,6115,4755,340,192,828
4,Alabama,1964,3407000,1358.7,466.6,784.1,108.0,213.1,163.0,9.3,...,29.1,46290,15898,26713,3679,7260,5555,316,397,992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3110,Wyoming,2015,586107,179.8,1902.6,300.6,1500.9,222.1,10.1,2.7,...,21.3,1054,11151,1762,8797,1302,59,16,173,125
3111,Wyoming,2016,585501,1957.3,302.5,1518.2,136.6,244.2,195.7,3.4,...,10.1,11460,1771,8889,800,1430,1146,20,205,59
3112,Wyoming,2017,579315,1830.4,275.0,1421.0,134.5,237.5,176.4,2.6,...,13.1,10604,1593,8232,779,1376,1022,15,263,76
3113,Wyoming,2018,577737,1785.1,264.0,1375.9,145.2,212.2,150.6,2.3,...,17.3,10313,1525,7949,839,1226,870,13,243,100
3114,Wyoming,2019,578759,1571.1,241.2,1206.7,123.2,217.4,147.6,2.2,...,11.6,9093,1396,6984,713,1258,854,13,324,67

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3115 entries, 0 to 3114
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state               3115 non-null   object
 1   year                3115 non-null   int64
 2   population          3115 non-null   int64
 3   property_rates_all  3115 non-null   float64
 4   rates_burglary      3115 non-null   float64
 5   rates_larceny       3115 non-null   float64
 6   rates_motor         3115 non-null   float64
 7   violent_rates_all   3115 non-null   float64
 8   rates_assault       3115 non-null   float64
 9   rates_murder        3115 non-null   float64
 10  rates_rape          3115 non-null   float64
 11  rates_robbery       3115 non-null   float64
 12  property_total_all  3115 non-null   int64
 13  total_burglary      3115 non-null   int64
 14  total_larceny       3115 non-null   int64
 15  total_motor         3115 non-null   int64
 16  violent_total_all   3115 non-null   int64
 17  total_assault       3115 non-null   int64
 18  total_murder        3115 non-null   int64
 19  total_rape          3115 non-null   int64
 20  total_robbery       3115 non-null   int64
dtypes: float64(9), int64(11), object(1)
memory usage: 511.2+ KB